steps:

# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'server'

- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'app'

# Build
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  dir: 'app'

# Deploy
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
  dir: 'server'
  timeout: '1600s'